[package]
name = "payload"
version = "0.1.0"
edition = "2021"

[dependencies]
cstr = "0.2.10"
ctor = "0.1.22"

[dependencies.windows]
version = "0.35.0"
features = ["Win32_UI_WindowsAndMessaging", "Win32_Foundation"]

[lib]
crate-type = ["cdylib"]
